### ISSUE TITLE
Fastlane: el shortdesc too long

### ISSUE THREAD

**Issue by IzzySoft** [mirfatif/MyLocation#15]
My scanner just reported `el/short_description.txt` having 98 chars. Fastlane allows for max 80 chars, so it will be truncated mid-word exactly at position 80. You might wish to adjust this so it doesn't look weird :wink:

**Comment by mirfatif** [comment]
It should already be truncated since the file hasn't been updated for 2 years :smile:
Let's keep it as it is until next release.

**Comment by IzzySoft** [comment]
Then I wonder why it came up with the monthly scan now. Maybe I had ignored it during the last runs? If it stays as-is, it will pop up every month here, so I might report it again (unless I simply delete or replace it here). But yeah, if the next release takes care for it, that's fine (except the next release is too far into the future :see_no_evil:). Thanks!

**Comment by mirfatif** [comment]
> except the next release is too far into the future 🙈

Possible :wink: 

So should I delete the file and push a commit here? Or you can do it on your side?

**Comment by IzzySoft** [comment]
I can delete it here. It then gets pulled again only in 1 of 2 cases: A new release is fetched, or I trigger a Fastlane pull manually. I've just changed it here (thanks to DeepL) to

    Βρείτε τις συντεταγμένες σας από τον πάροχο θέσης GPS & δικτύου

Not verified by a native speaker, though. DeepL translates it to "Find your coordinates from your GPS & network location provider" (cross-checked translating it back and forth). That's just 63 chars and thus should be fine.

**Comment by mirfatif** [comment]
Thanks.

**Comment by mirfatif** [comment]
Fixed in v1.06
