### ISSUE TITLE
Add altitude

### ISSUE THREAD

**Issue by woheller69** [mirfatif/MyLocation#3]
Can you please add the altitude?

**Comment by mirfatif** [comment]
Will be added in next release.

**Comment by woheller69** [comment]
hopefully also on F-Droid...

Ideal would be altitude above MSL in my view.
GPSTest seems to extract that from NMEA data.
https://github.com/barbeau/gpstest/blob/master/GPSTest/src/main/java/com/android/gpstest/util/NmeaUtils.java

**Comment by woheller69** [comment]
I just added altitude (from GPS) and altitude (MSL) from GPS NMEA strings in my fork. See commit above.
If you like I can make a PR.

**Comment by mirfatif** [comment]
Thank you for your interest. And I appreciate your contribution. Actually, as mentioned earlier, the altitude features (along with some other Play Store only features) has already been added to the app - not finished though. So after those commits your commit is no more mergeable with the local tree. But you can maintain your own tree if you want to.
